WebCSharp/WebCSharp/Models/EntityFrameWork/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebCSharp.Models.EntityFrameWork
{
    [Table("2121110054_Post")]

    public class Post:CommonAbstract
    {


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Mã chủ đề không được để trống")]
        public int Topic_Id { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]

        public string Title { get; set; }
        public string Slug { get; set; }
        [AllowHtml]
        public string Detail { get; set; }

        public string Image { get; set; }
        public string Type { get; set; }
        public string Metakey { get; set; }
        public string Metadesc { get; set; }
        [DefaultValue(1)]
        public int Status { get; set; }

        
        public virtual Topic Topics { get; set; }

    }
}

WebCSharp/WebCSharp/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCSharp.Models.EntityFrameWork;
using WebCSharp.Models;

namespace WebCSharp.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        // GET: Admin/Post
        private ApplicationDbContext _dbConect = new ApplicationDbContext();


        public ActionResult Index()
        {
            var items = _dbConect.Posts.OrderBy(x => x.Create_at).ToList();
            return View(items);
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Post model)
        {
            if (ModelState.IsValid)
            {
                model.Create_at = DateTime.Now;
                model.Update_at = DateTime.Now;
                model.Status = 1;
                model.Slug = WebCSharp.Models.Commons.Filter.FilterChar(model.Title);
               
                _dbConect.Posts.Add(model);
                _dbConect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //public ActionResult Edit(int id)
        //{
        //    var item = _dbConect.Topics.Find(id);
        //    return View(item);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(Topic model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _dbConect.Topics.Attach(model);
        //        model.Update_at = DateTime.Now;
        //        model.Status = 1;

        //        model.Slug = WebCSharp.Models.Commons.Filter.FilterChar(model.Name);
        //        _dbConect.Entry(model).Property(x => x.Name).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Slug).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Parent_Id).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Metadesc).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Metakey).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Update_at).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Update_By).IsModified = true;
        //        _dbConect.Entry(model).Property(x => x.Status).IsModified = true;
        //        _dbConect.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = _dbConect.Posts.Find(id);
            if (item != null)
            {
                _dbConect.Posts.Remove(item);
                _dbConect.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        public ActionResult Show(int id)
        {
            var item = _dbConect.Posts.Find(id);
            return View(item);
        }
    }
}

WebCSharp/WebCSharp/Areas/Admin/Views/Post/Add.cshtml
@model WebCSharp.Models.EntityFrameWork.Post
@{
    ViewBag.Title = "Thêm bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Thêm danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"><a href="/admin/post">Bài viết</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


}
<div class="card">
    @using (Html.BeginForm("Add", "Post", FormMethod.Post, new { }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false)
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-sm btn-danger">
                        <i class="fa fa-trash">Xóa</i>
                    </button>
                </div>

                <div class="col-md-6 text-right">
                    <button type="submit" class="btn bg-success">
                        <i class="fa-solid fa-save"></i> Lưu [Thêm]
                    </button>
                    <a href="/admin/topic" class="btn bg-success">
                        <i class="fa-solid fa-arrow-left"></i> Quay về danh sách
                    </a>

                </div>
            </div>

        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-md-9">
                    <div class="mb-3">
                        <label for="topic_id">Mã Chủ đề</label>
                        @Html.TextBoxFor(x => x.Topic_Id, new { @class = "form-control", @placeholder = "Nhập Mã chủ đề" })
                        @Html.ValidationMessageFor(x => x.Topic_Id, null, new { @class = "text-danger" })

                    </div>
                    <div class="mb-3">
                        <label for="title">Tiêu đề</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Nhập tên tiêu đề" })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })

                    </div>
                    <div class="mb-3">
                        <label for="detail">Chi tiết bài viết</label>

                        @Html.TextBoxFor(x => x.Detail, new { @class = "form-control", @placeholder = "metakey" ,@id="txtDetail" })
                       


                    </div>
                    
                </div>
                <div class="col-md-3">
                    <div class="mb-3">
                        <label for="exampleInputFile">File input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                @Html.TextBoxFor(x => x.Image, new { @id = "txtImage", @class = "form-control" })

                            </div>
                            <div class="input-group-append">
                                <input type="button" value="tải ảnh" onclick="BrowseServer('txtImage');"/>
                            </div>
                        </div>

                    </div>

                    <div class="mb-3">
                        <label for="type">Kiểu</label>
                        @Html.TextBoxFor(x => x.Type, new { @class = "form-control", @value = "" })

                    </div>
                    <div class="mb-3">
                        <label for="metakey">Từ khóa tìm kiếm</label>

                        @Html.TextBoxFor(x => x.Metakey, new { @class = "form-control", @placeholder = "metakey" })



                    </div>
                    <div class="mb-3">
                        <label for="metadesc">Metadesc</label>

                        @Html.TextBoxFor(x => x.Metadesc, new { @class = "form-control", @placeholder = "metakey" })



                    </div>


                </div>
            </div>


        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Footer
        </div>
    }
    <!-- /.card-footer-->
</div>
<!-- /.card -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent:'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
    }

WebCSharp/WebCSharp/Areas/Admin/Views/Post/Index.cshtml
@model IEnumerable<WebCSharp.Models.EntityFrameWork.Post>
@{
    ViewBag.Title = "Bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{

    <!-- Content Header (Page header) -->

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Quản lý Chủ đề</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"><a href="/admin/post">@ViewBag.Title</a></li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
}
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách Chủ đề</h3>

            <div class="card-tools">
                <a href="/admin/post/add" class="btn bg-success"><i class="fa fa-plus"></i> Thêm </a>
                <a class=" btn  bg-danger" href="/topic/trash"> <i class="fa fa-trash"></i>Thùng Rác</a>
            </div>
        </div>
    </div>
        <div class="card-body">



            <table class="table table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Hình ảnh</th>
                        <th>Mã Chủ đề</th>
                        <th>Tiêu đề</th>
                        <th>slug</th>
                        <th>Chức năng</th>


                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            <tr id="trow_@item.Id">
                                <td>
                                    @item.Id
                                </td>

                                <td><img src="@item.Image" width="50" /></td>
                                <td>@item.Topic_Id</td>
                                <td>@item.Title</td>
                                <td>@item.Slug</td>
                                <td>
                                    <a class="btn btn-sm btn-success" href="/admin/post/show/@item.Id"><i class="fa fa-eye"></i></a>

                                    <a href="/admin/post/edit/@item.Id" class="btn btn-sm btn-primary"><i class="fa fa-pen"></i></a>

                                    <a href="#" data-id="@item.Id"
                                       class="btn btn-sm btn-danger btnDelete" title="delete">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                    @if (@item.Status == 1)
                                    {
                                        <a href="" class="btn btn-sm btn-primary">
                                            <i class="fas fa-toggle-on"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="" class="btn btn-sm btn-danger">
                                            <i class="fas fa-toggle-off"></i>
                                        </a>
                                    }




                                </td>

                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào</td>
                        </tr>
                    }
                    @*@endforeach*@

                </tbody>
            </table>


            @*</div>*@
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

</section>
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không ?');
                if (conf == true) {
                    $.ajax({
                        url: '/admin/topic/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
}

WebCSharp/WebCSharp/Areas/Admin/Views/Post/Show.cshtml
@*@model IEnumerable<WebCSharp.Models.EntityFrameWork.Menu>*@
@model WebCSharp.Models.EntityFrameWork.Post

@{
    ViewBag.Title = "Chi tiết bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cập nhật danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"><a href="/admin/post">Bài viết</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


}
<section class="content">
    @Html.HiddenFor(x => x.Id)
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Chi tiết Menu</h3>

            <div class="card-tools">
                <a href="/admin/topic" class="btn bg-success"><i class="fa fa-arrow-left"></i> Quay lại </a>
            </div>
        </div>
        <div class="card-body">








            <div class="card-body">
                <table class="table table-bordered border-success table-hover ">
                    <thead class="bg-green">
                        <tr class="fs-1">
                            <th width="30%">
                                Tên trường
                            </th>
                            <th>
                                Giá trị
                            </th>
                        </tr>
                    </thead>
                    <tbody>



                        <tr>
                            <th>Id</th>
                            <td>@Model.Id</td>


                        </tr>
                        <tr>
                            <th>Hình ảnh</th>
                            <td><img src="@Model.Image" width="200"/></td>
                        </tr>
                        <tr>
                            <th>Mã chủ đề(topic)</th>
                            <td>@Model.Topic_Id</td>
                        </tr>
                        <tr>
                            <th>Tiêu đề</th>
                            <td>@Model.Title</td>
                        </tr>
                        <tr>
                            <th>Slug</th>
                            <td>@Model.Slug</td>
                        </tr>


                        <tr>
                            <th>Chi tiết</th>
                            <td>@Model.Detail</td>
                        </tr>
                        <tr>
                            <th>Kiểu</th>
                            <td>@Model.Type</td>
                        </tr>
                        <tr>
                            <th>Metakey</th>
                            <td>@Model.Metakey</td>
                        </tr>
                        <tr>
                            <th>Metadesc</th>
                            <td>@Model.Metadesc</td>
                        </tr>
                        <tr>
                            <th>Ngày tạo</th>
                            <td>@Model.Create_at</td>
                        </tr>
                        <tr>
                            <th>Người tạo</th>
                            <td>@Model.Create_By</td>
                        </tr>
                        <tr>
                            <th>Ngày sửa cuối</th>
                            <td>@Model.Update_at</td>
                        </tr>
                        <tr>
                            <th>Người sửa cuối</th>
                            <td>@Model.Update_By</td>
                        </tr>
                        <tr>
                            <th>Trạng thái</th>
                            <td>@Model.Status</td>
                        </tr>


                    </tbody>
                </table>
            </div>


            @*</div>*@
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

</section>
<!-- /.card -->