WebCSharp/WebCSharp/Models/EntityFrameWork/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebCSharp.Models.EntityFrameWork
{
    [Table("2121110054_Menu")]

    public class Menu:CommonAbstract
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(150, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Name { get; set; }
        public string Link { get; set; }
        public string Position { get; set; }
        [Required]
        public int Parent_Id { get; set; }
        
        public int Table_Id { get; set; }


        public string Type { get; set; }

        [DefaultValue(1)]
        public int Status { get; set; }
    }
}

WebCSharp/WebCSharp/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCSharp.Models;
using WebCSharp.Models.EntityFrameWork;


namespace WebCSharp.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext _dbConect = new ApplicationDbContext();
        // GET: Admin/Menu

        public ActionResult Index()
        {
            var items = _dbConect.Menus.ToList();
            return View(items);
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Menu model )
        {
            if (ModelState.IsValid)
            {
                model.Create_at = DateTime.Now;
                model.Update_at = DateTime.Now;
                model.Status = 1;
                model.Type = model.Name;
                model.Link = WebCSharp.Models.Commons.Filter.FilterChar(model.Name);
                _dbConect.Menus.Add(model);
                _dbConect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var item = _dbConect.Menus.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Menu model)
        {
            if (ModelState.IsValid)
            {
                _dbConect.Menus.Attach(model);
                model.Update_at = DateTime.Now;
                model.Status = 1;
                model.Type = model.Name;
                model.Link = WebCSharp.Models.Commons.Filter.FilterChar(model.Name);
                _dbConect.Entry(model).Property(x=>x.Name).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Link).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Position).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Parent_Id).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Table_Id).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Type).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Update_at).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Update_By).IsModified = true;
                _dbConect.Entry(model).Property(x => x.Status).IsModified = true;
                _dbConect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = _dbConect.Menus.Find(id);
            if (item != null)
            {
                _dbConect.Menus.Remove(item);
                _dbConect.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        public ActionResult Show(int id)
        {
            var item = _dbConect.Menus.Find(id);
            return View(item);
        }
    }
    

}

WebCSharp/WebCSharp/Areas/Admin/Views/Menu/Add.cshtml
@model WebCSharp.Models.EntityFrameWork.Menu
@{
    ViewBag.Title = "Thêm Menu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Thêm danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Danh mục</li>
                        <li class="breadcrumb-item active">Thêm mới danh mục</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


}
<div class="card">
    @using (Html.BeginForm("Add", "Menu", FormMethod.Post, new { }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false)
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-sm btn-danger">
                        <i class="fa fa-trash">Xóa</i>
                    </button>
                </div>

                <div class="col-md-6 text-right">
                    <button type="submit" class="btn bg-success">
                        <i class="fa-solid fa-save"></i> Lưu [Thêm]
                    </button>
                    <a href="/admin/menu" class="btn bg-success">
                        <i class="fa-solid fa-arrow-left"></i> Quay về danh sách
                    </a>

                </div>
            </div>

        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-md-9">
                    <div class="mb-3">
                        <label for="name">Tên Menu</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Nhập tên danh mục" })
                        @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })

                    </div>
                    @*<div class="mb-3">
                            <label for="link">Đường dẫn</label>

                            @Html.TextBoxFor(x => x.Link, new { @class = "form-control", @placeholder = "Đường dẫn" })
                            @Html.ValidationMessageFor(x => x.Link, null, new { @class = "text-danger" })


                        </div>*@
                    <div class="mb-3">
                        <label for="position">Vị trí</label>

                        @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @placeholder = "Vị trí" })



                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mb-3">
                        <label for="parent_id">Danh mục cha</label>
                        @Html.TextBoxFor(x => x.Parent_Id, new { @class = "form-control", @value = "0" })
                        @Html.ValidationMessageFor(x => x.Parent_Id, null, new { @class = "text-danger" })
                    </div>
                    <div class="mb-3">
                        <label for="sort_order">Vị trí sắp xếp</label>
                        @Html.TextBoxFor(x => x.Table_Id, new { @class = "form-control", @value = "0" })
                        @Html.ValidationMessageFor(x => x.Table_Id, null, new { @class = "text-danger" })
                    </div>
                    <div class="mb-3">
                        <label for="status">Trạng thái</label>
                        @Html.TextBoxFor(x => x.Status, new { @class = "form-control", @value = "1" })
                        @Html.ValidationMessageFor(x => x.Status, null, new { @class = "text-danger" })
                    </div>
                    @*<div class="mb-3">
                            <label for="image">Hình ảnh</label>
                            <input type="file" name="image" value="{{old('image')}}" id="image" class="form-control" placeholder="Thêm hình ảnh">

                        </div>*@

                </div>
            </div>      
            

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Footer
        </div>
    }
        <!-- /.card-footer-->
    </div>
<!-- /.card -->

WebCSharp/WebCSharp/Areas/Admin/Views/Menu/Edit.cshtml
@model WebCSharp.Models.EntityFrameWork.Menu
@{
    ViewBag.Title = "Cập nhật Menu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cập nhật danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Danh mục</li>
                        <li class="breadcrumb-item active">Cập nhật danh mục</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


}
<div class="card">
    @using (Html.BeginForm("Edit", "Menu", FormMethod.Post, new { }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(x=>x.Id)

        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-sm btn-danger">
                        <i class="fa fa-trash">Xóa</i>
                    </button>
                </div>

                <div class="col-md-6 text-right">
                    <button type="submit" class="btn bg-success">
                        <i class="fa-solid fa-save"></i> Lưu [Thêm]
                    </button>
                    <a href="/admin/menu" class="btn bg-success">
                        <i class="fa-solid fa-arrow-left"></i> Quay về danh sách
                    </a>

                </div>
            </div>

        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-md-9">
                    <div class="mb-3">
                        <label for="name">Tên Menu</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Nhập tên danh mục" })
                        @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })

                    </div>
                    @*<div class="mb-3">
                            <label for="link">Đường dẫn</label>

                            @Html.TextBoxFor(x => x.Link, new { @class = "form-control", @placeholder = "Đường dẫn" })
                            @Html.ValidationMessageFor(x => x.Link, null, new { @class = "text-danger" })


                        </div>*@
                    <div class="mb-3">
                        <label for="position">Vị trí</label>

                        @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @placeholder = "Vị trí" })



                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mb-3">
                        <label for="parent_id">Danh mục cha</label>
                        @Html.TextBoxFor(x => x.Parent_Id, new { @class = "form-control", @value = "0" })
                        @Html.ValidationMessageFor(x => x.Parent_Id, null, new { @class = "text-danger" })
                    </div>
                    <div class="mb-3">
                        <label for="sort_order">Vị trí sắp xếp</label>
                        @Html.TextBoxFor(x => x.Table_Id, new { @class = "form-control", @value = "0" })
                        @Html.ValidationMessageFor(x => x.Table_Id, null, new { @class = "text-danger" })
                    </div>
                    <div class="mb-3">
                        <label for="status">Trạng thái</label>
                        @Html.TextBoxFor(x => x.Status, new { @class = "form-control", @value = "1" })
                        @Html.ValidationMessageFor(x => x.Status, null, new { @class = "text-danger" })
                    </div>
                    @*<div class="mb-3">
                            <label for="image">Hình ảnh</label>
                            <input type="file" name="image" value="{{old('image')}}" id="image" class="form-control" placeholder="Thêm hình ảnh">

                        </div>*@

                </div>
            </div>


        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Footer
        </div>
    }
    <!-- /.card-footer-->
</div>
<!-- /.card -->

WebCSharp/WebCSharp/Areas/Admin/Views/Menu/Index.cshtml
@model IEnumerable<WebCSharp.Models.EntityFrameWork.Menu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{

    <!-- Content Header (Page header) -->

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Quản lý danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Danh mục</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
}
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách danh mục</h3>

            <div class="card-tools">
                <a href="/admin/menu/add" class="btn bg-success"><i class="fa fa-plus"></i> Thêm </a>
                <a class=" btn  bg-danger" href="/menu/trash"> <i class="fa fa-trash"></i>Thùng Rác</a>
            </div>
        </div>
        <div class="card-body">


           
                <table class="table table-bordered" id="myTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Tên Menu</th>
                            <th>slug Menu</th>
                            <th>Chức năng</th>


                        </tr>
                    </thead>
                    <tbody>
                        @*@foreach ($list_category as $category)*@
                        @if (Model != null && Model.Any())
                        {
                            var i = 1;
                            foreach(var item in Model)
                            {
                            <tr id="trow_@item.Id">
                                <td>
                                    <input type="checkbox" name="" id="">
                                </td>

                                <td>@i</td>
                                <td>@item.Name</td>
                                <td>@item.Link</td>
                                <td>
                                    <a class="btn btn-sm btn-success" href="/admin/menu/show/@item.Id"><i class="fa fa-eye"></i></a>

                                    <a href="/admin/menu/edit/@item.Id" class="btn btn-sm btn-primary"><i class="fa fa-pen"></i></a>
                                    
                                    <a href="#" data-id="@item.Id"
                                       class="btn btn-sm btn-danger btnDelete" title="delete">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                    @if (@item.Status == 1)
                                    {
                                        <a href="" class="btn btn-sm btn-primary">
                                            <i class="fas fa-toggle-on"></i>
                                        </a>
                                    }
                                    else
                                    {
                                    <a href="" class="btn btn-sm btn-danger">
                                        <i class="fas fa-toggle-off"></i>
                                    </a>
                                    }


                                  

                                </td>

                            </tr>
                                i++;
                            }

                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào</td>
                            </tr>
                        }
                            @*@endforeach*@

                        </tbody>
                </table>

            
            @*</div>*@
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

</section>
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không ?');
                if (conf == true) {
                    $.ajax({
                        url: '/admin/menu/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
    }

WebCSharp/WebCSharp/Areas/Admin/Views/Menu/Show.cshtml
@*@model IEnumerable<WebCSharp.Models.EntityFrameWork.Menu>*@
@model WebCSharp.Models.EntityFrameWork.Menu

@{
    ViewBag.Title = "Cập nhật Menu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cập nhật danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Menu</li>
                        <li class="breadcrumb-item active">Xem chi tiết menu</li>
                    </ol>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


}
<section class="content">
    @Html.HiddenFor(x => x.Id)
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Chi tiết Menu</h3>

            <div class="card-tools">
                <a href="/admin/menu" class="btn bg-success"><i class="fa fa-arrow-left"></i> Quay lại </a>
            </div>
        </div>
        <div class="card-body">








            <div class="card-body">
                <table class="table table-bordered border-success table-hover ">
                    <thead class="bg-green">
                        <tr class="fs-1">
                            <th width="30%">
                                Tên trường
                            </th>
                            <th>
                                Giá trị
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        
                        
                            <tr>
                                <th>Id</th>
                                <td>@Model.Id</td>


                            </tr>

                            <tr>
                                <th>Tên Menu</th>
                                <td>@Model.Name</td>
                            </tr>
                            <tr>
                                <th>Slug</th>
                                <td>@Model.Link</td>
                            </tr>
                            <tr>
                                <th>Sắp xếp</th>
                                <td>@Model.Position</td>
                            </tr>
                            <tr>
                                <th>Mã cấp cha</th>
                                <td>@Model.Parent_Id</td>
                            </tr>
                            <tr>
                                <th>Mã bảng</th>
                                <td>@Model.Table_Id</td>
                            </tr>
                            <tr>
                                <th>Kiểu</th>
                                <td>@Model.Type</td>
                            </tr>
                            <tr>
                                <th>Ngày tạo</th>
                                <td>@Model.Create_at</td>
                            </tr>
                            <tr>
                                <th>Người tạo</th>
                                <td>@Model.Create_By</td>
                            </tr>
                            <tr>
                                <th>Ngày sửa cuối</th>
                                <td>@Model.Update_at</td>
                            </tr>
                            <tr>
                                <th>Người sửa cuối</th>
                                <td>@Model.Update_By</td>
                            </tr>
                            <tr>
                                <th>Trạng thái</th>
                                <td>@Model.Status</td>
                            </tr>
                        

                    </tbody>
                </table>
            </div>


            @*</div>*@
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

</section>
<!-- /.card -->